### ISSUE TITLE
Replace template words with core issues

### ISSUE THREAD

**Issue by dayne** [FairbanksHackathon/fairbankshackathon.github.io#1]
# Fairbanks Hackathon Website

_rough cut at content_

We want to encourage fun hacking by Fairbanks Hackers. 

This website and the issue tracker associated 
## Need
- Creative space for tech folks in Fairbanks to connect around fun and meaningful challenges. 
- Publicly collect and iterate on ideas and challenges
- Connect fairbanks hackers to challenges in their local area
## How:
- Publicly curated issues and developed solution
- Do this publicly and openly.

**Comment by dayne** [comment]
Done!

**Comment by xoxotld** [comment]
Wow. It looks GREAT. Great words, too.
Excellent addition to the startup community.
Thank you both for pulling this together.
Let me know the best time to meet to make a plan going forward. 

And, no fo'get Startup Weekend starts 5:30 pm Fri. I'll forward the registration info to the team. Let me know if you think you're able to participate at all remotely - and if there is anything you need on my end to make that happen, and I'll see what I can do.

Juliet 

Juliet Shepherd
Tech Led Development Project Manager
Fairbanks Economic Development Corporation
330 Wendell St., Suite 100
Fairbanks, AK 99701
P: 907.452.2185
C: 907.385-7244
