### ISSUE TITLE
google analytics on website

### ISSUE THREAD

**Issue by dayne** [FairbanksHackathon/fairbankshackathon.github.io#4]
We should create a google analytics and google tag manager account for our website. 

Analytics gives us the ability to track and report on if we are getting people using our website. Is working on this worth it?

**Comment by xoxotld** [comment]
I'd say so. 
I'll plan to promote the site in conjunction with Innovate Alaska (2.0) & Alaska Startup Digest.
Let me know when after Sept 25 and Oct 8, or after Oct 24, would work to touch bases and make a plan going forward.

**Comment by dayne** [comment]
Added to the website.
